const cardData = [
  {
    team6: {
      tenure: "2023-2024",
      members: [
        {
          name: "Faraz Ghani",
          post: "President",
          description: "",
          image:
            "https://i.ibb.co/ZLNYDm3/Faraz.jpg",
          LinkedIn: "linkedin.com/in/farazg",
          Twitter: "",
        },
        {
          name: "Sarwat Aijaz",
          post: "Vice President",
          description: "",
          image:
            "https://i.ibb.co/QjgqWJ3/Vp-Sarwat-Aijaz.jpg",
          LinkedIn: "linkedin.com/in/sarwataijaz",
          Twitter: "",
        },
        {
          name: "Sachal Sahito",
          post: "Treasurer",
          description: "",
          image:
            "https://i.ibb.co/4tcYVzs/Treasurer-Sachal-Sahito.jpg",
          LinkedIn: "linkedin.com/in/muhammad-sachal-sahito-833ba2232",
          Twitter: "",
        },
        {
          name: "Gotam Kumar",
          post: "General Secretary",
          description: "",
          image:
            "https://i.ibb.co/GdT14HM/GS-Gotam-Kumar.jpg",
          LinkedIn: "linkedin.com/in/gotam-kumar-5239a525b",
          Twitter: "",
        },
        {
          name: "Ghulam Mustafa",
          post: "Joint Secretary",
          description: "",
          image:
            "https://i.ibb.co/G7SkWf3/JS-Ghulam-Mustafa.jpg",
          LinkedIn: "https://www.linkedin.com/in/ghulam-mustafa-23sw/",
          Twitter: "",
        },
        {
          name: "Masood Ali",
          post: "Head Director Management",
          description: "",
          image:
            "https://i.ibb.co/MS2zvxf/Head-management-Masood-Ali.png",
          LinkedIn: "linkedin.com/in/masood-ali-487116233",
          Twitter: "",
        },
        {
          name: "Humera Masood",
          post: "Director Management",
          description: "",
          image:
            "https://i.ibb.co/r3km8T8/Mangement-Humera-Masood.jpg",
          LinkedIn: "linkedin.com/in/humera-soomro-607245297",
          Twitter: "",
        },
        {
          name: "Soorat Ali",
          post: "Director Management",
          description: "",
          image:
            "https://i.ibb.co/S5yJRNb/Soorat-Management.jpg",
          LinkedIn: "linkedin.com/in/soorat-ali-3391aa289",
          Twitter: "",
        },
        {
          name: "Muhammad Ahmed",
          post: "Director Management",
          description: "",
          image:
            "https://i.ibb.co/nCGrMhb/Management-Ahmed-Siddiqui.jpg",
          LinkedIn: "linkedin.com/in/ahmedsidd-qui",
          Twitter: "",
        },
        {
          name: "Rutba Nisar",
          post: "Director Management",
          description: "",
          image:
            "https://i.ibb.co/hfZ58MC/Management-rutba-nisar.jpg",
          LinkedIn: "linkedin.com/in/rutbanisar05",
          Twitter: "",
        },
        {
          name: "Maryam Qureshi",
          post: "Head Director Designing",
          description: "",
          image:
            "https://i.ibb.co/pLzXbHy/Maryam-Qureshi.png",
          LinkedIn: "linkedin.com/in/maryam-qureshi-937a96250",
          Twitter: "",
        },
        {
          name: "Mahrukh Mahar",
          post: "Director Designing",
          description: "",
          image:
            "https://i.ibb.co/hfCM5dt/Design-Mahrukh-mahar.jpg",
          LinkedIn: "linkedin.com/in/",
          Twitter: "",
        },
        {
          name: "Mustafa",
          post: "Director Designing",
          description: "",
          image:
            "https://i.ibb.co/YPgrNCK/Design-Mustafa-Jan.jpg",
          LinkedIn: "linkedin.com/in/",
          Twitter: "",
        },
        {
          name: "Uroosham Memon",
          post: "Head Director Media",
          description: "",
          image:
            "https://i.ibb.co/GtVDKFx/Uroosham-Head-Media.jpg",
          LinkedIn: "linkedin.com/in/urooshammemon",
          Twitter: "",
        },
        {
          name: "Rubab Majid",
          post: "Director Media",
          description: "",
          image:
            "https://i.ibb.co/gyF3dJX/Rubab-Majid-Media.jpg",
          LinkedIn: "https://www.linkedin.com/in/rubab-majid-/",
          Twitter: "",
        },
        {
          name: "Hafsa Noor",
          post: "Director Media",
          description: "",
          image:
            "https://i.ibb.co/phd9GCb/Media-Hafsa-Noor-Khokhar.jpg",
          LinkedIn: "https://www.linkedin.com/in/hafsa-noor-295ab5261/",
          Twitter: "",
        },
        {
          name: "Aimon Zehra",
          post: "Director Media",
          description: "",
          image:
            "https://i.ibb.co/S7T8zGG/Media-Aimon-Zehra.jpg",
          LinkedIn: "linkedin.com/in/aimonzehra",
          Twitter: "",
        },
        {
          name: "Aiman Shaikh",
          post: "Head Director Editorial",
          description: "",
          image:
            "https://i.ibb.co/gwGwtCx/Head-editorial-Aiman-Shaikh.jpg",
          LinkedIn: "linkedin.com/in/aiman-shaikh-023949260",
          Twitter: "",
        },
        {
          name: "Mahad Shah Rashidi",
          post: "Director Editorial",
          description: "",
          image:
            "https://i.ibb.co/8KJR8gG/Editorial-Mahad-Rashdi.jpg",
          LinkedIn: "linkedin.com/in/shahgger",
          Twitter: "",
        },
        {
          name: "Varoon Kumar",
          post: "Head Director Videography",
          description: "",
          image:
            "https://i.ibb.co/gmGXzQV/Head-video-Varoon-Kumar.jpg",
          LinkedIn: "https://www.linkedin.com/in/varoon-kumar-250a1a252/",
          Twitter: "",
        },
        {
          name: "Rania Shah",
          post: "Director Videography",
          description: "",
          image:
            "https://i.ibb.co/sv0bDSm/Video-Rania-Shah.jpg",
          LinkedIn: "linkedin.com/in/rania-sadia-ba784a296",
          Twitter: "",
        },
        {
          name: "Zain Khan Awan",
          post: "Head Director Marketing",
          description: "",
          image:
            "https://i.ibb.co/ZzBK5jY/Head-marketing-Zain-Khan.jpg",
          LinkedIn: "linkedin.com/in/zain-khan-ba1664297",
          Twitter: "",
        },
        {
          name: "Abdul Haseeb",
          post: "Director Marketing",
          description: "",
          image:
            "https://i.ibb.co/7SqXgHz/Marketin-Abdul-Haseeb-Memon.jpg",
          LinkedIn: "https://www.linkedin.com/in/abdul-haseeb-memon-78681625b/",
          Twitter: "",
        },
        {
          name: "Taneesha Lohana",
          post: "Director Marketing",
          description: "",
          image:
            "https://i.ibb.co/THgCkwh/Market-Tanisha-Lohana.jpg",
          LinkedIn: "https://www.linkedin.com/in/taneesha-lohana-178005263/",
          Twitter: "",
        },
        {
          name: "Raza Zaeem",
          post: "Head Director Photography",
          description: "",
          image:
            "https://i.ibb.co/FxhpYm9/Head-photo-Zaeem-Raza.jpg",
          LinkedIn: "linkedin.com/in/zaeem-raza-20560125b",
          Twitter: "",
        },
        {
          name: "Nashra Jahejo",
          post: "Director Photography",
          description: "",
          image:
            "https://i.ibb.co/wwsBvPt/Photo-Nashra-Jahejo.jpg",
          LinkedIn: "https://www.linkedin.com/in/nashrah-jahejo-824965288/",
          Twitter: "",
        },
        {
          name: "Haram Rajput",
          post: "Head Director Logistics",
          description: "",
          image:
            "https://i.ibb.co/59kmQR1/Head-logistics-Mohammad-Haram-Rajput.jpg",
          LinkedIn: "linkedin.com/in/haram-rajput-221b94261",
          Twitter: "",
        },
        {
          name: "Jahanzaib Ansari",
          post: "Director Logistics",
          description: "",
          image:
            "https://i.ibb.co/b6NT4Qb/Jahanzaib-Logistics.jpg",
          LinkedIn: "linkedin.com/in/jahanzaib-ansari-b50b49296",
          Twitter: "",
        },
        {
          name: "Zeeshan Talpur",
          post: "Director Logistics",
          description: "",
          image:
            "https://i.ibb.co/XY3Rjsh/logistics-Zeeshan-Talpur.jpg",
          LinkedIn: "linkedin.com/in/zeeshan-talpur-4277b4252",
          Twitter: "",
        },
        {
          name: "Tayyaba Bhatti",
          post: "Head of Organization Council",
          description: "",
          image:
            "https://i.ibb.co/YcfTbmX/Head-oc-Tayyaba-Bhatti.jpg",
          LinkedIn: "linkedin.com/in/tayyaba-bhatti-955a3725b",
          Twitter: "",
        },
        {
          name: "Sumair Shahani",
          post: "Organization Council",
          description: "",
          image:
            "https://i.ibb.co/CnhzvxM/OC-Sumair-Ali-Shahani.jpg",
          LinkedIn: "linkedin.com/in/sumairalishahani",
          Twitter: "",
        },
        {
          name: "Abdul Basit",
          post: "Organization Council",
          description: "",
          image:
            "https://i.ibb.co/mqQL5T4/OC-basit-memon.jpg",
          LinkedIn: "linkedin.com/in/abdulbasit-m",
          Twitter: "",
        },
        {
          name: "Rafay Shakeel",
          post: "Organization Council",
          description: "",
          image:
            "https://i.ibb.co/4RFvQnn/OC-Rafay-Shakeel.jpg",
          LinkedIn: "linkedin.com/in/rafayshakeel",
          Twitter: "",
        },
        {
          name: "Rida Batool",
          post: "Organization Council",
          description: "",
          image:
            "https://i.ibb.co/4V4th31/OC-rida.jpg",
          LinkedIn: "linkedin.com/in/rida-batool-a42438297",
          Twitter: "",
        },
        {
          name: "Hadisa Naqvi",
          post: "Organization Council",
          description: "",
          image:
            "https://i.ibb.co/DrrDrvz/Hadisa-Naqvi-OC.jpg",
          LinkedIn: "linkedin.com/in/hadisa-naqvi-412b45282",
          Twitter: "",
        },
        {
          name: "Hadisa Syed",
          post: "Organization Council",
          description: "",
          image:
            "https://i.ibb.co/GQN8nQD/OC-Hadisa-Syed.jpg",
          LinkedIn: "linkedin.com/in/hadisa-fatima-syed-85537a266",
          Twitter: "",
        },
        {
          name: "Saria Nadeem",
          post: "Organization Council",
          description: "",
          image:
            "https://i.ibb.co/LYvrK6j/OC-Saria-Nadeem.jpg",
          LinkedIn: "https://www.linkedin.com/in/saria-nadeem-0124192b5/",
          Twitter: "",
        },
        {
          name: "Ghulam Hussain Khuhro",
          post: "Organization Council",
          description: "",
          image:
            "https://i.ibb.co/Y2SzQ6v/OC-Ghulam-Hussain-Khuhro.jpg",
          LinkedIn: "linkedin.com/in/ghulam-hussain-khuhro-5b4783243",
          Twitter: "",
        },
        {
          name: "Hassan ahmed",
          post: "Organization Council",
          description: "",
          image:
            "https://i.ibb.co/WzkV9vv/OC-Ha-Ssan-Ahme-D.jpg",
          LinkedIn: "https://www.linkedin.com/in/hassan-ahmed64/",
          Twitter: "",
        },
        {
          name: "Areej Fatima",
          post: "Organization Council",
          description: "",
          image:
            "https://i.ibb.co/R2k6hNs/OC-Areej-Fatima.jpg",
          LinkedIn: "linkedin.com/in/areejfatima13",
          Twitter: "",
        },
      ]
    },


    team5: {
      tenure: "2022-2023",
      members: [
        {
          name: "Syed Arham Abbas",
          post: "President",
          description: "",
          image:
            "https://i.ibb.co/Wvy5JNC/A1-FCBF73-DB45-49-AF-983-E-588-CDA789-D78-SES-MUET.jpg",
          LinkedIn: "",
          Twitter: "",
        },
        {
          name: "Ambar Arain",
          post: "Vice-President",
          description: "",
          image: "https://i.ibb.co/LkyxyX2/Ambar-Ambar-Arain.jpg",
          LinkedIn: "",
          Twitter: "",
        },
        {
          name: "Abdul Razzaq",
          post: "Treasurer",
          description: "",
          image:
            "https://i.ibb.co/VJsGVsz/CD1-E341-B-86-AE-4-A28-89-B2-188407-FBE3-B7-Abdul-Razzaq.jpg",
          LinkedIn: "",
          Twitter: "",
        },
        {
          name: "Muhammad Adil Memon",
          post: "General Secretary",
          description: "",
          image:
            "https://i.ibb.co/1GfqVKS/Snapchat-1874889576-Muhammad-Adil-memon.jpg",
          LinkedIn: "",
          Twitter: "",
        },
        {
          name: "Qurban Ali",
          post: "Joint Secretary",
          description: "",
          image: "https://i.ibb.co/Q9jZPxF/IMG-6592-Qurban-Ali-Ogahi.jpg",
          LinkedIn: "",
          Twitter: "",
        },
        {
          name: "Zarmeena Khan",
          post: "Director Management(Head)",
          description: "",
          image:
            "https://i.ibb.co/xjGgzhv/IMG-20230530-WA0037-Zarmeena-Khan.jpg",
          LinkedIn: "",
          Twitter: "",
        },
        {
          name: "Agha Durrez Khani",
          post: "Director Management",
          description: "",
          image:
            "https://i.ibb.co/wYtW0Fy/3-DFBF199-B4-D4-4-A22-95-DF-47-A483-D39-DD5-Agha-Durrez-Khan.jpg",
          LinkedIn: "",
          Twitter: "",
        },
        {
          name: "Ali Muhammad",
          post: "Director Management",
          description: "",
          image:
            "https://i.ibb.co/Cb4wkPq/2-CE66-F2-A-1-CD8-45-F3-909-A-9-C927-C1-C458-E.jpg",
          LinkedIn: "",
          Twitter: "",
        },
        {
          name: "Zohaib Khoso",
          post: "Director Management",
          description: "",
          image:"https://i.ibb.co/kDgkKFL/ses.jpg",
          LinkedIn: "",
          Twitter: "",
        },

        {
          name: "Minal Azhar",
          post: "Director Editorial(Head)",
          description: "",
          image:
            "https://i.ibb.co/ZS5jtPS/minal.jpg",
          LinkedIn: "",
          Twitter: "",
        },

        {
          name: "Ainab Qazi",
          post: "Editorial Officer",
          description: "",
          image: "https://i.ibb.co/jbvsjcx/IMG-0803-Ainab-Kazi.jpg",
          LinkedIn: "",
          Twitter: "",
        },
        {
          name: "Muhammad Daniyal",
          post: "Head Director Media ",
          description: "",
          image: "https://i.ibb.co/RYwPVbp/1673766399354-SES-MUET.jpg",
          LinkedIn: "",
          Twitter: "",
        },
        {
          name: "Muhammad Sarosh",
          post: "Director Media",
          description: "",
          image:
            "https://i.ibb.co/CQ4qnCj/photo-output-Mohammad-sarosh-Shaikh.jpg",
          LinkedIn: "",
          Twitter: "",
        },
        {
          name: "Aashish Kumar",
          post: "Director Media",
          description: "",
          image:
            "https://i.ibb.co/QbB6f4V/a8341fc5-e216-4fe2-8319-df535bf8810f-Aashish-Kumar.jpg",
          LinkedIn: "",
          Twitter: "",
        },
        {
          name: "Uroosham Memon",
          post: "Director Media",
          description: "",
          image:
            "https://i.ibb.co/Sx5y6sf/Picsart-23-03-05-15-18-50-397-Uroosham-Memon.jpg",
          LinkedIn: "",
          Twitter: "",
        },
        {
          name: "Faraz Ghani",
          post: "Head Director of videography ",
          description: "",
          image: "https://i.ibb.co/vzvWzJd/faraz-faraz-temp.jpg",
          LinkedIn: "",
          Twitter: "",
        },
        {
          name: "Varoon Kumar",
          post: "Director of Videography",
          description: "",
          image:
            "https://i.ibb.co/P5L8KfQ/IMG-20220207-WA0093-Varoon-Kumar.jpg",
          LinkedIn: "",
          Twitter: "",
        },
        {
          name: "Sabrina Abro",
          post: "Director videography",
          description: "",
          image: "https://i.ibb.co/kcjBpzz/IMG-8556-Sabrina-Abro.jpg",
          LinkedIn: "",
          Twitter: "",
        },
        {
          name: "Hurain",
          post: "Director Videography",
          description: "",
          image: "https://i.ibb.co/z6zDbZJ/Director-Videography.jpg",
          LinkedIn: "",
          Twitter: "",
        },
        {
          name: "Faeez Ahmed Qureshi ",
          post: "Director Designer(Head)",
          description: "",
          image: "https://i.ibb.co/jfSpsC6/SAVE-20220601-063331-FUJ.jpg",
          LinkedIn: "",
          Twitter: "",
        },
        {
          name: "Faiz Nadeem",
          post: "Director Designe",
          description: "",
          image: "https://i.ibb.co/frjPnJP/419-C1140-Engrfaiz-Nadeem.jpg",
          LinkedIn: "",
          Twitter: "",
        },
        {
          name: "Maryam Qureshi",
          post: "Director Designing",
          description: "",
          image:
            "https://i.ibb.co/4K05jz8/IMG-20230527-WA0008-Uroosham-Memon.jpg",
          LinkedIn: "",
          Twitter: "",
        },
        {
          name: " Zahoor Ahmed",
          post: "Director Graphics Design",
          description: "",
          image:
            "https://i.ibb.co/qkNMwkP/IMG-20220317-223647-605-Zahoor-Ahmed.jpg",
          LinkedIn: "",
          Twitter: "",
        },
        {
          name: "Muzafar Ibrahim",
          post: "Head Director Logistics ",
          description: "",
          image:
            "https://i.ibb.co/X3gMt5t/95-E8-FC9-F-95-FE-4-B22-9-BD0-2-A11-A27-C9794-Muzafar-Mahar.jpg",
          LinkedIn: "",
          Twitter: "",
        },
        {
          name: "Muhammad Haram Rajput",
          post: "Director Logistics",
          description: "",
          image: "https://i.ibb.co/DQqJCNj/IMG-0612-Mohammad-Haram-Rajput.jpg",
          LinkedIn: "",
          Twitter: "",
        },
        {
          name: "M Abdullah Khan ",
          post: "Director Photography",
          description: "",
          image:
            "https://i.ibb.co/JFDgMM3/1-G9-A8993-Muhammad-Abdullah-Khan.jpg",
          LinkedIn: "",
          Twitter: "",
        },
        {
          name: "Kashish",
          post: "Director Photography",
          description: "",
          image: "https://i.ibb.co/hKt5CMm/IMG-1764-Chowdhry-Kashish.jpg",
          LinkedIn: "",
          Twitter: "",
        },
        {
          name: "Uzair Hussain",
          post: " Head Director Marketing",
          description: "",
          image: "https://i.ibb.co/QYqsj29/uzairs-Uzair-Hussain.jpg",
          LinkedIn: "",
          Twitter: "",
        },

        {
          name: "Gotam kumar",
          post: "Director Marketing",
          description: "",
          image: "https://i.ibb.co/yfWkJnk/IMG-20220112-WA0016-1-Gotam-Kumar.jpg",
          LinkedIn: "",
          Twitter: "",
        },
        {
          name: "Ali Raza",
          post: "Director Marketing",
          description: "",
          image: "https://i.ibb.co/K9swFxw/419-C6194-Ali-Raza.jpg",
          LinkedIn: "",
          Twitter: "",
        },

        {
          name: "Usama Nayab",
          post: "Lead Developers Teams.",
          description: "",
          image:
            "https://i.ibb.co/KzDp8ys/71-AAB90-B-7-F04-4564-8-C89-0902560-E26-DB-usama-nayab.jpg",
          LinkedIn: "",
          Twitter: "",
        },
        {
          name: "Kashaf Abdullah ",
          post: "Developer",
          description: "",
          image:
            "https://i.ibb.co/XsbxBrj/kashafpic.jpg",
          LinkedIn: "",
          Twitter: "",
        },

        {
          name: "Muhammad Arayan",
          post: "Developer",
          description: "",
          image: "https://i.ibb.co/FYFk8D1/1680198541314-memon-aryu.jpg",
          LinkedIn: "",
          Twitter: "",
        },
        {
          name: "Fahad Hussain",
          post: "Director Developer",
          description: "",
          image:
            "https://i.ibb.co/PmtQWCT/inbound2782392963145104133-Fahad-Hussain.jpg",
          LinkedIn: "",
          Twitter: "",
        },
        {
          name: "Summaiya khan",
          post: " Organzization Council (Head)",
          description: "",
          image:
            "https://i.ibb.co/Bs7MMWG/IMG-20230321-WA0038-Summiya-Khan.jpg",
          LinkedIn: "",
          Twitter: "",
        },

        {
          name: "Hafsa Noor",
          post: "Organization Council ",
          description: "",
          image: "https://i.ibb.co/bL3GCH7/1-Hafsa-Noor-Khokhar.jpg",
          LinkedIn: "",
          Twitter: "",
        },

        {
          name: "Sachal Sahito",
          post: "Organization Council ",
          description: "",
          image: "https://i.ibb.co/Vq4jvDm/419-C5496-Sachal-Sahito.jpg",
          LinkedIn: "",
          Twitter: "",
        },
        {
          name: "Nayab Nisar ",
          post: "Organization Council ",
          description: "",
          image: "https://i.ibb.co/SxhnBWn/IMG-20230314-182209-Nayab-Nisar.jpg",
          LinkedIn: "",
          Twitter: "",
        },

        {
          name: "Taneesha",
          post: "Organization Council ",
          description: "",
          image:
            "https://i.ibb.co/hybxdY1/d672e713-4049-4701-b59e-67372bb41b56-Tanisha-Lohana.jpg",
          LinkedIn: "",
          Twitter: "",
        },
        ,
        {
          name: "Rida Shah ",
          post: "Organization Council ",
          description: "",
          image:
            "https://i.ibb.co/vkDcBQj/Screenshot-20230529-010222-Ridda-Batool.jpg",
          LinkedIn: "",
          Twitter: "",
        },

        {
          name: "Zain khan",
          post: "Organization Council ",
          description: "",
          image:
            "https://i.ibb.co/JksB2g8/d4de72e8-d524-434a-82d6-c2f9c695f039-Original-Zain-Khan.jpg",
          LinkedIn: "",
          Twitter: "",
        },
        {
          name: "Areeba Syed",
          post: "Organization Council ",
          description: "",
          image: "https://i.ibb.co/V2KPvnw/Hashmi-Areeba-Syed.jpg",
          LinkedIn: "",
          Twitter: "",
        },
        ,
        {
          name: "Aina Saeed",
          post: "Organization Council ",
          description: "",
          image: "https://i.ibb.co/dWLvqZk/419-C5181-Aina-Saeed.jpg",
          LinkedIn: "",
          Twitter: "",
        },
        ,
        {
          name: "Sarwat Aijaz",
          post: "Organization Council ",
          description: "",
          image:
            "https://i.ibb.co/8zwJvgb/IMG-20230416-203156-106-Pak-Blink-Army.jpg",
          LinkedIn: "",
          Twitter: "",
        },

        ,
        {
          name: "Tayyaba Bhatti",
          post: "Organziation council",
          description: "",
          image:
            "https://i.ibb.co/Gx5jqfj/IMG-20230322-WA0012-Tayyaba-Bhatti.jpg",
          LinkedIn: "",
          Twitter: "",
        },
      ],
    },
    team4: {
      tenure: "2021-2022",
      members: [
        {
          name: "Tabish Rehmatullah",
          post: "President",
          description: "Public Speaker, Entrepreneur",
          image:
            "https://i.ibb.co/6nDbkKn/4-A2-E873-F-69-F4-4523-BAC7-9-C45-BC93-CD80.jpg",
          LinkedIn: "http://linkedin.com/in/tabishrehmatullah",
          Twitter: "https://twitter.com/TabishRMemon",
        },
        {
          name: "Muskan",
          post: "Vice-President",
          description: "Data Science Enthusiast",
          image: "https://i.ibb.co/9ZHGXQX/Muskan.jpg",
          LinkedIn: "https://www.linkedin.com/in/muskanmughal/",
          Twitter: null,
        },
        {
          name: "Chaudhary Faisal",
          post: "Treasurer",
          description: "Business Analyst",
          image:
            "https://i.ibb.co/5kwxTrD/37-BDB6-DB-C553-46-FB-9-C44-C3-BB1-B1-C01-EA.jpg",
          LinkedIn: "https://www.linkedin.com/in/ch-faisal-aa85b321b",
          Twitter: null,
        },
        {
          name: "Isha Bhutto",
          post: "General Secretery",
          description: "Video Editor, New tech recruit.",
          image: "https://i.ibb.co/FXsT4W8/1641562995798.jpg",
          LinkedIn: "https://www.linkedin.com/mwlite/in/isha-bhutto-29359621b",
          Twitter: "https://twitter.com/ishabhutto",
        },
        {
          name: "Tooba",
          post: "Joint Secretery",
          description: "Passionate Python Developer",
          image:
            "https://i.ibb.co/Wpk9gYk/27e7888b-2dbb-4d5c-bf9d-eee28883745b.jpg",
          LinkedIn: "https://www.linkedin.com/in/tooba-akhtar-52715b196/",
          Twitter: "https://twitter.com/Toobaay_arain",
        },
        {
          name: "Kashaf",
          post: "Director Management(Head)",
          description: "Web developer and web designer",
          image: "https://i.ibb.co/XsbxBrj/kashafpic.jpg",
          LinkedIn: "https://www.linkedin.com/in/kashaf-abdullah-482246207/",
          Twitter: null,
        },
        {
          name: "Godhawari Khatri",
          post: "Director Mnagement",
          description: "Java Developer",
          image: "https://i.ibb.co/mFNCWpr/godhawari.jpg",
          LinkedIn: "https://www.linkedin.com/in/godhawari-khatri-700038236/",
          Twitter: null,
        },
        {
          name: "Naveed KK",
          post: "Director Management",
          description: "Passionate Flutter Developer",
          image: "https://i.ibb.co/Y2TgrYq/Pics-Art-12-03-10-39-57.jpg",
          LinkedIn: "https://www.linkedin.com/in/naveed-kaimkhani-499450220",
          Twitter: null,
        },
        {
          name: "Zaid Ahmed Soomro",
          post: "Director Management",
          description: "Devoted Techie, Coding Ninja",
          image: "https://i.ibb.co/qYnNRvp/FB-IMG-1644979419805.jpg",
          LinkedIn: "https://www.linkedin.com/in/iamzaidsoomro/",
          Twitter: "https://twitter.com/ZaidSoomro17",
        },
        {
          name: "Farheen Qazi",
          post: "Director Editorial(Head)",
          description: "Product Designer, 3D Modelling Enthusiast",
          image: "https://bit.ly/farheen-qazi-director-editorial",
          LinkedIn: "https://www.linkedin.com/in/farheen-qazi-679a2320a/",
          Twitter: "https://twitter.com/FarheenQazi0",
        },
        {
          name: "Junaid Aslam",
          post: "Director Editorial",
          description: "A Competitive Programmer",
          image: "https://i.ibb.co/hBVXsxM/PU2ap-SR-400x400.jpg",
          LinkedIn: "https://www.linkedin.com/in/junaid-aslam-4824b51b8",
          Twitter: "https://twitter.com/JunaidAslam084",
        },
        {
          name: "Faeez Ahmed",
          post: "Director Designer (Head)",
          description: "Graphic Designer and Artist",
          image: "https://i.ibb.co/kQcz3Vb/IMG-20220210-101854-608.jpg",
          LinkedIn: "http://www.linkedin.com/in/faeez-ahmed-934780221",
          Twitter: null,
        },

        {
          name: "Muhammad Usama",
          post: "Director Designer",
          description: "Wordpress Developer",
          image:
            "https://i.ibb.co/bPVw05z/Whats-App-Image-2022-05-31-at-12-16-55-PM.jpg",
          LinkedIn: "https://www.linkedin.com/in/muhammad-usama-655301225",
          Twitter: "https://twitter.com/Muhamma49097453",
        },
        {
          name: "Paras Soomro",
          post: "Director Designer",
          description: "Graphic Designer",
          image:
            "https://i.ibb.co/wCdd3hL/Whats-App-Image-2022-05-31-at-10-52-04-PM.jpg",
          LinkedIn: "https://www.linkedin.com/in/paras-soomro-38a08420b",
          Twitter: null,
        },
        {
          name: "Muhammad Usman",
          post: "Director Marketing(Head)",
          description: "Dedicated Flutter Dev",
          image: "https://i.ibb.co/J7jGvtR/IMG-20220527-113815.jpg",
          LinkedIn:
            "https://www.linkedin.com/in/muhammad-usman-soomro-73b4a6220",
          Twitter:
            "https://twitter.com/MuhamadUsman786?t=MP4IdB1LyoEK3Fi_ut2FmA&s=09",
        },
        {
          name: "Laraib Ayoub",
          post: "Director Marketing",
          description: "Passionate Flutter Developer",
          image:
            "https://i.ibb.co/K5hy59m/Whats-App-Image-2022-05-28-at-11-18-31-PM.jpg",
          LinkedIn: "https://www.linkedin.com/in/laraib-ayoub-53451122b",
          Twitter: null,
        },
        {
          name: "Kubra Ghafoor",
          post: "Director Media(Head)",
          description: "UI/UX Designer",
          image:
            "https://i.ibb.co/WK9bfR4/Whats-App-Image-2022-05-26-at-9-23-59-PM.jpg",
          LinkedIn:
            "https://www.linkedin.com/in/kubra-ghafoor-a8291b20a/?originalSubdomain=pk",
          Twitter: "https://twitter.com/KubraGhafoor",
        },
        {
          name: "Anjali Kumari",
          post: "Director Media",
          description: "Pythonista",
          image:
            "https://i.ibb.co/CmdKBQn/D430-AB40-F4-CF-406-A-92-D9-460822257-B42.jpg",
          LinkedIn: "https://www.linkedin.com/in/anjli-kumari-288506228/",
          Twitter:
            "https://twitter.com/AnjliDeepani?s=20&t=t-flVrmytqY5p4jkP6NZLA",
        },
        {
          name: "Muhammad Daniyal",
          post: "Director Media",
          description: "Love to Capture",
          image: "https://i.ibb.co/hB3r9Qm/1653762777611.jpg",
          LinkedIn: null,
          Twitter:
            "https://twitter.com/Muhamma26048074?t=bYFYzaOn0rQ71uBC9BZEmw&s=09",
        },
        {
          name: "Hasnain Seelro ",
          post: "Director Logistics",
          description: " DevOps Enthusiast",
          image: "https://i.ibb.co/pnBptD9/IMG-1618.jpg",
          LinkedIn: "https://www.linkedin.com/in/hasnain-seelro-89155a22a/",
          Twitter: "https://twitter.com/Hasnain53482373",
        },
        {
          name: "Syed Arham Abbas",
          post: "Director Logistics",
          description: "Passionate Cybersecurity analyst",
          image:
            "https://i.ibb.co/yPdrLPN/8-EA9-CEC6-8245-417-A-A9-B5-364-CBA1-D2-B1-F.jpg",
          LinkedIn: null,
          Twitter: null,
        },
        {
          name: "Summaiya Khan",
          post: "Director Photography ",
          description: "Novice UI/UX Designer",
          image: "https://i.ibb.co/nRLmtbP/IMG-20220505-160247-272.webp",
          LinkedIn: "https://www.linkedin.com/in/summaiya-khan-63554021b/",
          Twitter: "https://twitter.com/Summaiyaa_khan",
        },
        {
          name: "Moiz Azam",
          post: "Director Photography",
          description: "Love to capture",
          image: "https://i.ibb.co/Z8cWVRr/AKS-6077.jpg",
          LinkedIn: "https://www.linkedin.com/in/moiz-azam-549435215",
          Twitter: null,
        },
        {
          name: "Shumaim",
          post: "Organizing Council(Head)",
          description: "Creative UI/UX desinger",
          image:
            "https://i.ibb.co/wMtT2kf/888-F1586-DC98-4081-BA33-56-E31-A8-A5-DC2.jpg",
          LinkedIn: "http://linkedin.com/in/shumaim-liaquat",
          Twitter: null,
        },
        {
          name: "Adarsh Kumar",
          post: "Organizing Council",
          description: "Java Developer",
          image: "https://i.ibb.co/H20W3FY/1629917930966.jpg",
          LinkedIn: "https://www.linkedin.com/in/adarsh-kumar-76921421b",
          Twitter: "https://twitter.com/adarsh_rohera",
        },
        {
          name: "Faiz Nadeem",
          post: "Organizing Council",
          description: "Web developer",
          image: "https://i.ibb.co/JzJFJB8/1651265657944.jpg",
          LinkedIn: "https://www.linkedin.com/in/faiz-nadeem-337a5b1b7",
          Twitter: null,
        },
        {
          name: "Ali Raza",
          post: "Organizing Council",
          description: "An Artist in Tech World",
          image:
            "https://i.ibb.co/MpyHw90/Whats-App-Image-2022-05-31-at-12-22-34-PM.jpg",
          LinkedIn: null,
          Twitter: null,
        },
        {
          name: "Alishba Aleem",
          post: "Organizing Council",
          description: "Novice Programmer",
          image: "https://i.ibb.co/8Y1d3LH/IMG-20201120-WA0003.jpg",
          LinkedIn: null,
          Twitter: null,
        },
        {
          name: "Ayesha Ali",
          post: "Organizing Council",
          description: "A passionate Girl in tech world",
          image:
            "https://i.ibb.co/z2jcxND/Whats-App-Image-2022-05-27-at-2-30-48-PM.jpg",
          LinkedIn: "https://www.linkedin.com/in/ayesha-ali-53892120a/",
          Twitter: null,
        },
        {
          name: "Amber Arain",
          post: "Organizing Council",
          description: "Web Designer and Developer",
          image: "https://i.ibb.co/nc3BQLK/IMG-20220210-WA0010.jpg",
          LinkedIn: "https://www.linkedin.com/in/ambar-arain-71786720a/",
          Twitter: "https://twitter.com/ambar_arain",
        },
        {
          name: "Hira Amir",
          post: "Organizing Council",
          description: "An inquisitive Web Developer and Designer",
          image:
            "https://i.ibb.co/ZzsWDRd/Whats-App-Image-2022-05-31-at-12-00-58-PM.jpg",
          LinkedIn: "https://www.linkedin.com/in/hiraaamir/",
          Twitter: "https://twitter.com/hira_bux",
        },
        {
          name: "Amaar Raza",
          post: "Organizing Council",
          description: "React.js Developer",
          image: "https://i.ibb.co/DMXs7ZX/amaar.jpg",
          LinkedIn: "https://www.linkedin.com/in/amaar-raza-a30aa8211/",
          Twitter: null,
        },
        {
          name: "Zarmeena Khan",
          post: "Organizing Council",
          description: "User Interface Designer",
          image: "https://i.ibb.co/cYDfzZV/IMG-20220609-WA0003.jpg",
          LinkedIn: "https://www.linkedin.com/in/zarmeena-khan-68259221b",
          Twitter: null,
        },
      ],
    },

    team3: {
      tenure: "2020-2021",
      members: [
        {
          name: "Yusra",
          post: "President",
          image: "https://i.ibb.co/HxsP1mp/1653583383770.jpg",
          LinkedIn: "https://www.linkedin.com/in/yusra-fatima-779726204",
          Twitter: "https://twitter.com/yusrakhoso",
        },
        {
          name: "Iqra Ghani",
          post: "Vice President",
          image: "https://i.ibb.co/K9CNM6g/1628719299077.jpg",
          LinkedIn: "https://www.linkedin.com/in/iqra-ghani-69a964199/",
          Twitter: null,
        },
        {
          name: "Ramsha",
          post: "Treasurer",
          image: "https://i.ibb.co/f1GBvjy/ramsha.jpg",
          LinkedIn: "https://www.linkedin.com/in/ramsha-daudpota-3b80491b6/",
          Twitter: "https://twitter.com/RamshaDaudpota",
        },
        {
          name: "Altamash",
          post: "General Secretery",
          image: "https://i.ibb.co/NpwsNmb/1641044713158.jpg",
          LinkedIn: "https://www.linkedin.com/in/altamash-khuwaja/",
          Twitter: "https://twitter.com/AltamashAkber",
        },
        {
          name: "Maha Isham",
          post: "Joint Secretery",
          image: "https://i.ibb.co/HLyJ30n/1638104217133.jpg",
          LinkedIn: "https://www.linkedin.com/in/maha-khan-5b95021ba/",
          Twitter: null,
        },
        {
          name: "Rashid Wassan",
          post: "Director Management",
          image: "https://i.ibb.co/dDny7K3/1653636233405.jpg",
          LinkedIn: "https://www.linkedin.com/in/rashidwassan/",
          Twitter: "https://twitter.com/rashidwassaan",
        },
        {
          name: "Bakhtawar",
          post: "Director Management",
          image: null,
          LinkedIn: null,
          Twitter: null,
        },
        {
          name: "Muskan",
          post: "Director Management",
          image: "https://i.ibb.co/9ZHGXQX/Muskan.jpg",
          LinkedIn: "https://www.linkedin.com/in/muskanmughal/",
          Twitter: null,
        },
        {
          name: "Umesh",
          post: "Director Management",
          image: "https://i.ibb.co/KK1ddqL/1608555369211.jpg",
          LinkedIn: "https://www.linkedin.com/in/umesh-bansari-796123198/",
          Twitter: "https://twitter.com/BansariUmesh",
        },
        {
          name: "Dua Mir",
          post: "Director Editorial",
          image: "https://i.ibb.co/Vw4DRDT/47ftxz-T5-400x400.jpg",
          LinkedIn: null,
          Twitter: "https://twitter.com/DuaaMiir",
        },
        {
          name: "Shahzad Panwhar",
          post: "Director Editorial",
          image: "https://i.ibb.co/TRkzbBS/1636121956096.jpg",
          LinkedIn: "https://www.linkedin.com/in/shahzad-panhwar-1ab64820a/",
          Twitter: null,
        },
        {
          name: "Rohat Iftikhar",
          post: "Director Designer",
          image: "https://i.ibb.co/5rKxdcF/1629632270705.jpg",
          LinkedIn: "https://www.linkedin.com/in/rohat-iftikhar/",
          Twitter: "https://twitter.com/IftikharRohat",
        },
        {
          name: "Misbah",
          post: "Director Designer",
          image: null,
          LinkedIn: null,
          Twitter: null,
        },
        {
          name: "Shumaila",
          post: "Director Designer",
          image: "https://i.ibb.co/QcfqnN5/1654072846516.jpg",
          LinkedIn: "https://www.linkedin.com/in/shumaila-brohi-35b6611a6/",
          Twitter: "https://twitter.com/BrohiShumaila",
        },
        {
          name: "Laiba",
          post: "Director Marketing",
          image: "https://i.ibb.co/tKGj34b/1-14a-Wrmw-qk-Vv-HHPts-PH7s-Q.jpg",
          LinkedIn: "https://www.linkedin.com/in/laiba-memon-940b711a8/",
          Twitter: null,
        },
        {
          name: "Aemon Jabbar",
          post: "Director Marketing",
          image: "https://i.ibb.co/y8K4s73/49372579.jpg",
          LinkedIn: "https://www.linkedin.com/in/aemonjabbar/",
          Twitter: "https://twitter.com/Aemonjabbar2000",
        },
        {
          name: "Saqib Liaquat",
          post: "Director Marketing",
          image: "https://i.ibb.co/kyDvVcy/1637080435507.jpg",
          LinkedIn: "https://www.linkedin.com/in/saqib-liaquat-260110120/",
          Twitter: null,
        },
        {
          name: "Fahad",
          post: "Director Media",
          image: "https://i.ibb.co/q0yjQYg/fahad-chandio-Klmhq-Zv.webp",
          LinkedIn: "https://www.linkedin.com/in/fahad-chandio-3b63531a1",
          Twitter: null,
        },
        {
          name: "Dua Ali",
          post: "Director Media",
          image: "https://i.ibb.co/ThgZB1g/1631888884670.jpg",
          LinkedIn: "https://www.linkedin.com/in/dua-ali-abbasi-61b75019b/",
          Twitter: null,
        },
        {
          name: "Sana Faiz",
          post: "Director Media",
          image: null,
          LinkedIn: null,
          Twitter: null,
        },
        {
          name: "Mubashir",
          post: "Director Logistics",
          image:
            "https://i.ibb.co/MkLNntb/275122254-1200417870496290-8882352159459391622-n.jpg",
          LinkedIn: "https://www.linkedin.com/in/mubi-says/",
          Twitter: null,
        },
        {
          name: "Abdul Aziz",
          post: "Director Logistics",
          image: "https://i.ibb.co/pQ1G7LS/1613892636188.jpg",
          LinkedIn: "https://www.linkedin.com/in/abdul-aziz-khoso-19sw64/",
          Twitter: null,
        },
        {
          name: "Tabish",
          post: "Director Photography",
          image:
            "https://i.ibb.co/6nDbkKn/4-A2-E873-F-69-F4-4523-BAC7-9-C45-BC93-CD80.jpg",
          LinkedIn: "http://linkedin.com/in/tabishrehmatullah",
          Twitter: "https://twitter.com/TabishRMemon",
        },
        {
          name: "Nikash",
          post: "Director Photography",
          image: null,
          LinkedIn: "https://www.linkedin.com/in/nikash-mansukhani-a9585820b/",
          Twitter: null,
        },
        {
          name: "Gulwish",
          post: "Organizing Council",
          image: null,
          LinkedIn: "https://www.linkedin.com/in/gulwish-dilawar-98012b1ab/",
          Twitter: null,
        },
        {
          name: "Amna Afzal",
          post: "Organizing Council",
          image: null,
          LinkedIn: null,
          Twitter: null,
        },
        {
          name: "Aisha Isani",
          post: "Organizing Council",
          image: "https://i.ibb.co/ZxLDcB1/1637316323220.jpg",
          LinkedIn: "https://www.linkedin.com/in/aisha-isani-298967226/",
          Twitter: "https://twitter.com/aishaisani/",
        },
        {
          name: "Sumair Tahir",
          post: "Organizing Council",
          image: "https://i.ibb.co/3SsRYKB/1653080147291.jpg",
          LinkedIn: "https://www.linkedin.com/in/sumair-memon-b81867184/",
          Twitter: null,
        },
        {
          name: "Rumisa",
          post: "Organizing Council",
          image: "https://i.ibb.co/47C5Gzr/rumisa-khan-9b6z1qk.webp",
          LinkedIn: "https://www.linkedin.com/in/rumisa-khan-323408206/",
          Twitter: null,
        },
        {
          name: "Noor Ahmed",
          post: "Organizing Council",
          image: "https://i.ibb.co/5W9gNYH/1639606762673.jpg",
          LinkedIn: "https://www.linkedin.com/in/noor-ahmed-b8b8b8/",
          Twitter: null,
        },
        {
          name: "Nittalia Zaheer",
          post: "Organizing Council",
          image: "https://i.ibb.co/8gMJSMt/1646980990540.jpg",
          LinkedIn: "https://www.linkedin.com/in/nittalia-zaheer-2372a1234/",
          Twitter: "https://twitter.com/NittaliaZ",
        },
        {
          name: "Fiza Rasheed",
          post: "Organizing Council",
          image: null,
          LinkedIn: "https://www.linkedin.com/in/fiza-rasheed-2b45741b3/",
          Twitter: null,
        },
        {
          name: "Hira Hanif",
          post: "Organizing Council",
          image: null,
          LinkedIn: null,
          Twitter: null,
        },
        {
          name: "Nimra Khan",
          post: "Organizing Council",
          image: "https://i.ibb.co/RNwhxVV/1634240371834.jpg",
          LinkedIn: "https://www.linkedin.com/in/nimra-khan-015044207/",
          Twitter: null,
        },
        {
          name: "Sameer Akhtari",
          post: "Organizing Council",
          image: "https://i.ibb.co/PzDgwL4/1616000207288.jpg",
          LinkedIn: "https://www.linkedin.com/in/sameer-akhtari-386ba295/",
          Twitter: null,
        },
        {
          name: "Farwa Shaikh",
          post: "Organizing Council",
          image:
            "https://i.ibb.co/hmNB6pJ/266354815-1110013369826536-3579249973461481512-n.jpg",
          LinkedIn: "https://www.linkedin.com/in/farwah-shaikh/",
          Twitter: null,
        },
      ],
    },
    team2: {
      tenure: "2019-2020",
      members: [
        {
          name: "Abdul Samad",
          post: "President",
          LinkedIn: null,
          Twitter: null,
          description: null,
          image: "https://i.ibb.co/HgmNfjs/FB-IMG-1654330000698.jpg",
        },
        {
          name: "Saira Bano",
          post: "Vice President",
          LinkedIn: null,
          Twitter: null,
          description: null,
          image: "https://i.ibb.co/1bVF972/FB-IMG-1654329986174.jpg",
        },
        {
          name: "Atib Adil",
          post: "Treasurer",
          LinkedIn: null,
          Twitter: null,
          description: null,
          image: "https://i.ibb.co/XWNZb7J/FB-IMG-1654329995434.jpg",
        },
        {
          name: "Servech Ali",
          post: "General Secretery",
          LinkedIn: null,
          Twitter: null,
          description: null,
          image: "https://i.ibb.co/RhWf4vY/FB-IMG-1654329993402.jpg",
        },
        {
          name: "Inayat Ali",
          post: "Head Director Operations",
          LinkedIn: null,
          Twitter: null,
          description: null,
          image: "https://i.ibb.co/k0NxHyF/FB-IMG-1654330021912.jpg",
        },
        {
          name: "Hamza Shaikh",
          post: "Head Director General ",
          LinkedIn: null,
          Twitter: null,
          description: null,
          image: "https://i.ibb.co/zQzWrzK/FB-IMG-1654330017909.jpg",
        },
        {
          name: "Ali Siyal",
          post: "Head Director Media",
          LinkedIn: null,
          Twitter: null,
          description: null,
          image: "https://i.ibb.co/Tq57JNq/FB-IMG-1654330045855.jpg",
        },
        {
          name: "Yar Muhammad",
          post: "Head Director Logistics",
          LinkedIn: null,
          Twitter: null,
          description: null,
          image: "https://i.ibb.co/2cNxf11/FB-IMG-1654330039669.jpg",
        },
        {
          name: "Khubaib Khatri",
          post: "Head Director Photography",
          LinkedIn: null,
          Twitter: null,
          description: null,
          image: "https://i.ibb.co/DgzBscT/FB-IMG-1654330035119.jpg",
        },
        {
          name: "Fiza Azam",
          post: "Head Director Designing",
          LinkedIn: null,
          Twitter: null,
          description: null,
          image: "https://i.ibb.co/VM08ZGw/FB-IMG-1654330028575.jpg",
        },
        {
          name: "Mahnoor",
          post: "Director Operations",
          LinkedIn: null,
          Twitter: null,
          description: null,
          image: "https://i.ibb.co/vmYGGz9/FB-IMG-1654330023958.jpg",
        },
        {
          name: "Sara Aftab",
          post: "Director General",
          LinkedIn: null,
          Twitter: null,
          description: null,
          image: "https://i.ibb.co/3dZRQWd/FB-IMG-1654330019957.jpg",
        },
        {
          name: "Afhsan Hanif",
          post: " Director Media",
          LinkedIn: null,
          Twitter: null,
          description: null,
          image: "https://i.ibb.co/8N64wc5/FB-IMG-1654330048730.jpg",
        },
        {
          name: "Sandesh Gangwani",
          post: "Director Logistics",
          LinkedIn: null,
          Twitter: null,
          description: null,
          image: "https://i.ibb.co/TLRvrBC/FB-IMG-1654330041699.jpg",
        },
        {
          name: "Asad Jatoi",
          post: "Director Photography",
          LinkedIn: null,
          Twitter: null,
          description: null,
          image: "https://i.ibb.co/McLC4W6/FB-IMG-1654330037101.jpg",
        },
        {
          name: "Asad Rajput",
          post: "Director Designing",
          LinkedIn: null,
          Twitter: null,
          description: null,
          image: "https://i.ibb.co/JsxNZJn/FB-IMG-1654330030721.jpg",
        },
        {
          name: "Kashaf Irshad",
          post: "Director Operations",
          LinkedIn: null,
          Twitter: null,
          description: null,
          image: "https://i.ibb.co/xgvHMz5/FB-IMG-1654330026607.jpg",
        },
        {
          name: "Damini Mukhi",
          post: " Director Media",
          LinkedIn: null,
          Twitter: null,
          description: null,
          image: "https://i.ibb.co/ySrRnLw/FB-IMG-1654330050813.jpg",
        },
        {
          name: "Jawad Chandio",
          post: "Director Logistics",
          LinkedIn: null,
          Twitter: null,
          description: null,
          image: "https://i.ibb.co/XXzSkFH/FB-IMG-1654330043700.jpg",
        },
        {
          name: "Urmila",
          post: "Director Designing",
          LinkedIn: null,
          Twitter: null,
          description: null,
          image: "https://i.ibb.co/VDvTyXW/FB-IMG-1654330032674.jpg",
        },
      ],
    },
    team1: {
      tenure: "2018-2019",
      members: [
        {
          name: "Haris Ahmed",
          post: "President",
          LinkedIn: null,
          Twitter: null,
          description: null,
          image: "https://i.ibb.co/LJySQ69/FB-IMG-1656753428358.jpg",
        },
        {
          name: "Mashal",
          post: "Vice President",
          LinkedIn: null,
          Twitter: null,
          description: null,
          image: "https://i.ibb.co/jwbnkLB/FB-IMG-1656753430335.jpg",
        },
        {
          name: "Sanaullah",
          post: "Treasurer",
          LinkedIn: null,
          Twitter: null,
          description: null,
          image: "https://i.ibb.co/wyKt5PB/FB-IMG-1656753439291.jpg",
        },
        {
          name: "Hira Abid",
          post: "General Secretery",
          LinkedIn: null,
          Twitter: null,
          description: null,
          image: "https://i.ibb.co/TBThPpR/FB-IMG-1656753432592.jpg",
        },
        {
          name: "Bhagia Sheri",
          post: "Director General",
          LinkedIn: null,
          Twitter: null,
          description: null,
          image: "https://i.ibb.co/KXbM17Y/FB-IMG-1656753442061.jpg",
        },
        {
          name: "Saira Bano",
          post: "Director General ",
          LinkedIn: null,
          Twitter: null,
          description: null,
          image: "https://i.ibb.co/dPBpS8p/FB-IMG-1656753487453.jpg",
        },
        {
          name: "Abdul Samad",
          post: "Director General",
          LinkedIn: null,
          Twitter: null,
          description: null,
          image: "https://i.ibb.co/gvtPX5j/FB-IMG-1656753489555.jpg",
        },
        {
          name: "Mussaib Rasheed",
          post: "Director Photography",
          LinkedIn: null,
          Twitter: null,
          description: null,
          image: "https://i.ibb.co/xGWmqwM/FB-IMG-1656753491661.jpg",
        },
        {
          name: "Aqib Raza",
          post: "Director Photography",
          LinkedIn: null,
          Twitter: null,
          description: null,
          image: "https://i.ibb.co/X8Hq9Qh/FB-IMG-1656753504103.jpg",
        },
        {
          name: "Khubaib",
          post: "Director Photography",
          LinkedIn: null,
          Twitter: null,
          description: null,
          image: "https://i.ibb.co/v1H6kp9/FB-IMG-1656753507803.jpg",
        },
        {
          name: "Asmatullah Zubair",
          post: "Director Logistic",
          LinkedIn: null,
          Twitter: null,
          description: null,
          image: "https://i.ibb.co/68ybyrQ/FB-IMG-1656753510095.jpg",
        },
        {
          name: "Ghulam Mustafa",
          post: "Director Logistics",
          LinkedIn: null,
          Twitter: null,
          description: null,
          image: "https://i.ibb.co/R2vhv90/FB-IMG-1656753513083.jpg",
        },
        {
          name: "Ateeb Adil",
          post: "Director Logistics",
          LinkedIn: null,
          Twitter: null,
          description: null,
          image: "https://i.ibb.co/n80rS3z/FB-IMG-1656753515083.jpg",
        },
        {
          name: "Servech Ali",
          post: "Director Media",
          LinkedIn: null,
          Twitter: null,
          description: null,
          image: "https://i.ibb.co/x2nnr5X/FB-IMG-1656753517234.jpg",
        },
        {
          name: "Pooja",
          post: "Director Media",
          LinkedIn: null,
          Twitter: null,
          description: null,
          image: "https://i.ibb.co/QF0r6fm/FB-IMG-1656753519247.jpg",
        },
        {
          name: "Roofa",
          post: "Director Media",
          LinkedIn: null,
          Twitter: null,
          description: null,
          image: "https://i.ibb.co/rfnqhxr/FB-IMG-1656753526078.jpg",
        },
        {
          name: "Komal",
          post: "Director Media",
          LinkedIn: null,
          Twitter: null,
          description: null,
          image: "https://i.ibb.co/PChhtmL/FB-IMG-1656753528296.jpg",
        },
        {
          name: "Nida Zafar",
          post: "Director Design",
          LinkedIn: null,
          Twitter: null,
          description: null,
          image: "https://i.ibb.co/jzcQg4Q/FB-IMG-1656753532243.jpg",
        },
        {
          name: "Muhammad Muzammil",
          post: "Director Design",
          LinkedIn: null,
          Twitter: null,
          description: null,
          image: "https://i.ibb.co/72F8kDc/FB-IMG-1656753534879.jpg",
        },
        {
          name: "Pir Hamid Ali",
          post: "Director Design",
          LinkedIn: null,
          Twitter: null,
          description: null,
          image: "https://i.ibb.co/HFPZ9hC/FB-IMG-1656753536873.jpg",
        },
      ],
    },
  },
];

export default cardData;
